// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDct0-RV1YvLuPtzlACpVjvy8QrEEo9EiY',
    appId: '1:446638575430:web:db18c8f85553070d50df47',
    messagingSenderId: '446638575430',
    projectId: 'ai-powerrusme',
    authDomain: 'ai-powerrusme.firebaseapp.com',
    storageBucket: 'ai-powerrusme.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlAVlyXkIJCuaTFA2mhphRs5DFKAwCNnI',
    appId: '1:446638575430:android:b293e6e1e982bab050df47',
    messagingSenderId: '446638575430',
    projectId: 'ai-powerrusme',
    storageBucket: 'ai-powerrusme.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtT41z-f8SrOaUrZS0P4_sBG78Xu9NeTU',
    appId: '1:446638575430:ios:ce8b9209f5936b6450df47',
    messagingSenderId: '446638575430',
    projectId: 'ai-powerrusme',
    storageBucket: 'ai-powerrusme.firebasestorage.app',
    iosBundleId: 'com.example.aiPowerResume',
  );
}
